{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\nscripts\\test_login.py:20: Exception"}, "start": 1620954700914, "stop": 1620954700914, "uuid": "28a945be-8eb1-4231-a7b9-4c2b7b0061fb", "historyId": "e06d2c901627b19e67f3eda09ef5150c", "testCaseId": "2003ba1f0fbc5dbc400e66eda03af1c4", "fullName": "scripts.test_login#test_broken", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "AUTOBVT-I54QPM4"}, {"name": "thread", "value": "6708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}